/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.ui;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import poly.com.dao.NhanVienDAO;
import poly.com.modal.KhacHangTT;
import poly.com.modal.NhanVien;
import poly.com.utils.Auth;
import poly.com.utils.MsgBox;
import poly.com.utils.XImage;

/**
 *
 * @author nhatt
 */
public class MainForm extends javax.swing.JFrame {

    NhanVienDAO nvDAO= new NhanVienDAO();
    public MainForm() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btn_qrcode = new javax.swing.JButton();
        btn_donHang = new javax.swing.JButton();
        btn_nhapKho = new javax.swing.JButton();
        btn_qrcode1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        btn_qrcode2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        btn_nhapKho1 = new javax.swing.JButton();
        btn_qrcode3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnQLtk = new javax.swing.JMenuItem();
        mnDoimk = new javax.swing.JMenuItem();
        mnClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnDSSP = new javax.swing.JMenuItem();
        MnNCC = new javax.swing.JMenuItem();
        MnLHH = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mni_dsHD = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(252, 253, 152));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/logo.png"))); // NOI18N

        jToolBar1.setFloatable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/sanpham.png"))); // NOI18N
        jButton1.setText("Sản phẩm");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/hoadon.png"))); // NOI18N
        jButton2.setText("Loại sản phẩm");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/khachHang.png"))); // NOI18N
        jButton3.setText("Khách Hàng TT");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator3);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/nhanvien.png"))); // NOI18N
        jButton4.setText("Nhân Viên");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/doitac.png"))); // NOI18N
        jButton5.setText("Nhà Cung Cấp");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator5);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/doanhthu.png"))); // NOI18N
        jButton6.setText("Doanh Thu");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);
        jToolBar1.add(jSeparator6);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/Gear-icon.png"))); // NOI18N
        jButton7.setText("Trợ Giúp");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator7);

        jPanel2.setBackground(new java.awt.Color(252, 253, 152));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Boy.png"))); // NOI18N
        jLabel1.setText("Nhân viên hiện hành:");

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 0, 51));
        lblUser.setText("Họ và tên");

        lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Alarm.png"))); // NOI18N
        lbl.setText("Thời gian: ");

        lblTimer.setText("Thời gian thực");

        lbl_img.setBackground(new java.awt.Color(204, 0, 153));
        lbl_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(lblTimer))
                .addGap(20, 20, 20))
            .addComponent(lbl_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Quản lý bán hàng");

        btn_qrcode.setBackground(new java.awt.Color(0, 108, 215));
        btn_qrcode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_qrcode.setForeground(new java.awt.Color(255, 255, 255));
        btn_qrcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/qrcode.png"))); // NOI18N
        btn_qrcode.setText("BarCode");
        btn_qrcode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_qrcode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_qrcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qrcodeActionPerformed(evt);
            }
        });

        btn_donHang.setBackground(new java.awt.Color(0, 108, 215));
        btn_donHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_donHang.setForeground(new java.awt.Color(255, 255, 255));
        btn_donHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/donhang.png"))); // NOI18N
        btn_donHang.setText("Đơn hàng");
        btn_donHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_donHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_donHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donHangActionPerformed(evt);
            }
        });

        btn_nhapKho.setBackground(new java.awt.Color(0, 108, 215));
        btn_nhapKho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_nhapKho.setForeground(new java.awt.Color(255, 255, 255));
        btn_nhapKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/nhapkho.png"))); // NOI18N
        btn_nhapKho.setText("Nhập kho");
        btn_nhapKho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nhapKho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhapKhoActionPerformed(evt);
            }
        });

        btn_qrcode1.setBackground(new java.awt.Color(0, 108, 215));
        btn_qrcode1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_qrcode1.setForeground(new java.awt.Color(255, 255, 255));
        btn_qrcode1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/xuatkho.png"))); // NOI18N
        btn_qrcode1.setText("Xuất kho");
        btn_qrcode1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_qrcode1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_qrcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qrcode1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Quản lý kho hàng");

        btn_qrcode2.setBackground(new java.awt.Color(0, 108, 215));
        btn_qrcode2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_qrcode2.setForeground(new java.awt.Color(255, 255, 255));
        btn_qrcode2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/tonkho.png"))); // NOI18N
        btn_qrcode2.setText("Kho hàng");
        btn_qrcode2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_qrcode2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_qrcode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qrcode2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Báo cáo - Thống kê");

        btn_nhapKho1.setBackground(new java.awt.Color(0, 108, 215));
        btn_nhapKho1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_nhapKho1.setForeground(new java.awt.Color(255, 255, 255));
        btn_nhapKho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/doanhso.png"))); // NOI18N
        btn_nhapKho1.setText("Doanh thu");
        btn_nhapKho1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nhapKho1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nhapKho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhapKho1ActionPerformed(evt);
            }
        });

        btn_qrcode3.setBackground(new java.awt.Color(0, 108, 215));
        btn_qrcode3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_qrcode3.setForeground(new java.awt.Color(255, 255, 255));
        btn_qrcode3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/loinhuan.png"))); // NOI18N
        btn_qrcode3.setText("Lợi nhuận");
        btn_qrcode3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_qrcode3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_qrcode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qrcode3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/banner3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_qrcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_nhapKho, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_qrcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_donHang, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_qrcode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_nhapKho1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_qrcode3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_donHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_qrcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_qrcode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_nhapKho, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_qrcode2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_qrcode3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_nhapKho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 690));

        jMenu1.setText("Tài khoản");

        mnQLtk.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnQLtk.setText("QL tài khoản");
        mnQLtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQLtkActionPerformed(evt);
            }
        });
        jMenu1.add(mnQLtk);

        mnDoimk.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnDoimk.setText("Đổi mật khẩu");
        mnDoimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDoimkActionPerformed(evt);
            }
        });
        jMenu1.add(mnDoimk);

        mnClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnClose.setText("Đăng xuất");
        mnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCloseActionPerformed(evt);
            }
        });
        jMenu1.add(mnClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sản phẩm");

        MnDSSP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        MnDSSP.setText("Danh sách sản phẩm");
        MnDSSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnDSSPActionPerformed(evt);
            }
        });
        jMenu2.add(MnDSSP);

        MnNCC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        MnNCC.setText("Nhà cung cấp");
        MnNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnNCCActionPerformed(evt);
            }
        });
        jMenu2.add(MnNCC);

        MnLHH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        MnLHH.setText("Loại hàng hoá ");
        MnLHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLHHActionPerformed(evt);
            }
        });
        jMenu2.add(MnLHH);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("QL hoá đơn");

        mni_dsHD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mni_dsHD.setText("Danh sách hoá đơn");
        mni_dsHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_dsHDActionPerformed(evt);
            }
        });
        jMenu8.add(mni_dsHD);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem5.setText("Đơn hàng");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuBar1.add(jMenu8);

        jMenu7.setText("QL kho hàng");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Hàng nhập kho");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Hàng xuất kho");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Kho hàng");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jCheckBoxMenuItem1.setText("Danh sách nhập kho");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setText("Danh sách xuất kho");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Thống kê");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setText("Lợi nhuận");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem11.setText("Doanh Thu");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Trợ giúp");

        jCheckBoxMenuItem3.setText("Trợ giúp");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Giới thiệu sản phẩm");

        jMenuItem1.setText("Giới thiệu sản phẩm");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_donHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donHangActionPerformed
        new ThemHoaDon(this, true).setVisible(true);
    }//GEN-LAST:event_btn_donHangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openQuanlySP(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        openQuanlySP(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new QuanLyKhachHangTT(this, true).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if(Auth.isManager()){
             new QuanLyNhanVien(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new QLNhaCungCap(this, true).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mni_dsHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_dsHDActionPerformed
        new QuanLyHoaDon(this, true).setVisible(true);
    }//GEN-LAST:event_mni_dsHDActionPerformed

    private void mnDoimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoimkActionPerformed
        // TODO add your handling code here:
//        QuenMatKhau fogetMK = new QuenMatKhau(this, true);
        new QuenMatKhau(this, true).setVisible(true);

    }//GEN-LAST:event_mnDoimkActionPerformed

    private void btn_qrcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qrcodeActionPerformed
        new ThemHoaDon(this, true).setVisible(true);
    }//GEN-LAST:event_btn_qrcodeActionPerformed

    private void btn_nhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhapKhoActionPerformed
        
        if(Auth.isLogin()){
        if(Auth.isNVKK()){
            openQuanlyxuatnhaphang(1);
        }
        else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
        }
    }//GEN-LAST:event_btn_nhapKhoActionPerformed

    private void btn_qrcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qrcode1ActionPerformed
        
         if(Auth.isLogin()){
        if(Auth.isNVKK()){
            openQuanlyxuatnhaphang(3);
        }
        else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
        }
    }//GEN-LAST:event_btn_qrcode1ActionPerformed

    private void btn_qrcode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qrcode2ActionPerformed
        openQuanlyxuatnhaphang(0);
    }//GEN-LAST:event_btn_qrcode2ActionPerformed

    private void btn_nhapKho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhapKho1ActionPerformed
        if(Auth.isManager()){
        new ThongKe(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
            
    }//GEN-LAST:event_btn_nhapKho1ActionPerformed

    private void btn_qrcode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qrcode3ActionPerformed
        if(Auth.isManager()){
        new ThongKe(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
    }//GEN-LAST:event_btn_qrcode3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(Auth.isManager()){
        new ThongKe(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void mnQLtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQLtkActionPerformed
        new QuanLyNhanVien(this, true).setVisible(true);
    }//GEN-LAST:event_mnQLtkActionPerformed

    private void mnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCloseActionPerformed
        System.exit(0);
        new DangNhap(this, true).setVisible(true);
    }//GEN-LAST:event_mnCloseActionPerformed

    private void MnDSSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnDSSPActionPerformed
        openQuanlySP(0);
    }//GEN-LAST:event_MnDSSPActionPerformed

    private void MnNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnNCCActionPerformed
        new QLNhaCungCap(this, true).setVisible(true);
    }//GEN-LAST:event_MnNCCActionPerformed

    private void MnLHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLHHActionPerformed
        openQuanlySP(1);
    }//GEN-LAST:event_MnLHHActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new QuanLyHoaDon(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       if(Auth.isManager()){
        new ThongKe(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        if(Auth.isManager()){
        new ThongKe(this, true).setVisible(true);
        }else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
//        openQuanlyxuatnhaphang(1);
        if(Auth.isLogin()){
        if(Auth.isNVKK()){
            openQuanlyxuatnhaphang(1);
        }
        else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
        }
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
//        openQuanlyxuatnhaphang(3);
        if(Auth.isLogin()){
        if(Auth.isNVKK()){
            openQuanlyxuatnhaphang(3);
        }
        else{
            MsgBox.alert(this, "Bạn không có quyền ");
        }
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        openQuanlyxuatnhaphang(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        openQuanlyxuatnhaphang(2);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        openQuanlyxuatnhaphang(4);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new TroGiup(this, true).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        // TODO add your handling code here:
                new TroGiup(this, true).setVisible(true);

    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openGioiThieu();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    private void init() {
        this.setIconImage(XImage.getAppIcon());  
        setLocationRelativeTo(null);
        new ManHinhChao(this, true).setVisible(true);
        new DangNhap(this, true).setVisible(true);
        this.setAvatar();
        this.setOclock();
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnDSSP;
    private javax.swing.JMenuItem MnLHH;
    private javax.swing.JMenuItem MnNCC;
    private javax.swing.JButton btn_donHang;
    private javax.swing.JButton btn_nhapKho;
    private javax.swing.JButton btn_nhapKho1;
    private javax.swing.JButton btn_qrcode;
    private javax.swing.JButton btn_qrcode1;
    private javax.swing.JButton btn_qrcode2;
    private javax.swing.JButton btn_qrcode3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JMenuItem mnClose;
    private javax.swing.JMenuItem mnDoimk;
    private javax.swing.JMenuItem mnQLtk;
    private javax.swing.JMenuItem mni_dsHD;
    // End of variables declaration//GEN-END:variables

    private void setAvatar() {
        NhanVien nv = Auth.user;
        lblUser.setText(nv.getHoTen());
        ImageIcon icon = XImage.read(nv.getImg());
        lbl_img.setIcon(icon);
        lbl_img.setText("");
    }

    private void setOclock() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat fomarter = new SimpleDateFormat("hh:mm:ss a");
                String text = fomarter.format(now);
                lblTimer.setText(text);
            }
        }).start();
    }
        private void openQuanlyxuatnhaphang(int index) {
                QuanLyNhapXuatHang2 tkwin = new QuanLyNhapXuatHang2(this, true);
                tkwin.setVisible(true);
                tkwin.selectTab(index);
        }
               private void openQuanlySP(int index) {
                QuanLySanPham tkwin = new QuanLySanPham(this, true);
                tkwin.setVisible(true);
                tkwin.selectTab(index);
        }
               private void openGioiThieu() {
        try {
            Desktop.getDesktop().browse(new File("GT/Ministop.html").toURI());
        } catch (Exception e) {
            MsgBox.alert(this, "Không tìm thấy file ");
        }
    }
}
