/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.ui;

import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import poly.com.dao.LoaiHangDAO;
import poly.com.dao.SanPhamDAO;
import poly.com.modal.LoaiHang;
import poly.com.modal.SanPham;
import poly.com.utils.Auth;
import poly.com.utils.GenerateQRCode;
import poly.com.utils.MsgBox;
import poly.com.utils.XImage;
import poly.com.utils.XSqueezeString;

/**
 *
 * @author nhatt
 */
public class QuanLySanPham extends javax.swing.JDialog {

    /**
     * Creates new form QuanLySanPham
     */
        public void selectTab(int index){
        jTabbedPane1.setSelectedIndex(index);
    }
    public QuanLySanPham(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init();
        btn_moi.setEnabled(false);
        //lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("E:\\Java_FPT\\PRO104_DuAn1\\Project\\QuanLySieuThi\\images\\omo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sp = new javax.swing.JTable();
        btn_in = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_loaiHang = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaLH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGIaMua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHSD = new javax.swing.JTextField();
        txtVAT = new javax.swing.JTextField();
        lblVAT = new javax.swing.JLabel();
        txtDonVi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_moi = new javax.swing.JButton();
        btn_themsp = new javax.swing.JButton();
        btn_suasp = new javax.swing.JButton();
        btn_xoasp = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_loaiSP = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btn_themlsp = new javax.swing.JButton();
        btn_sualsp = new javax.swing.JButton();
        btn_xoalsp = new javax.swing.JButton();
        txtTenLoai = new javax.swing.JTextField();
        txtMaLoai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_moilh = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(253, 252, 152));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÝ SẢN PHẨM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        lbl_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/omo.png"))); // NOI18N
        lbl_img.setOpaque(true);
        lbl_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imgMouseClicked(evt);
            }
        });

        tbl_sp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Giá mua", "Giá bán", "HSD", "VAT", "Đơn vị tính", "Ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_spMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sp);

        btn_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Print.png"))); // NOI18N
        btn_in.setLabel("In thành file");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Search.png"))); // NOI18N
        btn_timKiem.setText("Tìm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        lst_loaiHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_loaiHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lst_loaiHang);

        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Properties.png"))); // NOI18N
        jLabel11.setText("Loại hàng:");

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Mã LH: ");

        txtMaLH.setEditable(false);

        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Mã SP:");

        txtMaSP.setEditable(false);

        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Giá mua:");

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Giá bán:");

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("HSD:");

        lblVAT.setForeground(new java.awt.Color(0, 102, 102));
        lblVAT.setText("VAT:");

        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Đơn vị:");

        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Tên SP:");

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        btn_moi.setBackground(new java.awt.Color(0, 153, 51));
        btn_moi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_moi.setForeground(new java.awt.Color(255, 255, 255));
        btn_moi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Numbered list.png"))); // NOI18N
        btn_moi.setText("Làm mới form");
        btn_moi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_moiMouseClicked(evt);
            }
        });
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });
        jPanel5.add(btn_moi);

        btn_themsp.setBackground(new java.awt.Color(0, 153, 51));
        btn_themsp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_themsp.setForeground(new java.awt.Color(255, 255, 255));
        btn_themsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Add.png"))); // NOI18N
        btn_themsp.setText("Thêm sản phẩm");
        btn_themsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themspMouseClicked(evt);
            }
        });
        btn_themsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themspActionPerformed(evt);
            }
        });
        jPanel5.add(btn_themsp);

        btn_suasp.setBackground(new java.awt.Color(0, 153, 51));
        btn_suasp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_suasp.setForeground(new java.awt.Color(255, 255, 255));
        btn_suasp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Edit.png"))); // NOI18N
        btn_suasp.setText("Cập nhật");
        btn_suasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaspActionPerformed(evt);
            }
        });
        jPanel5.add(btn_suasp);

        btn_xoasp.setBackground(new java.awt.Color(0, 102, 102));
        btn_xoasp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_xoasp.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoasp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Delete.png"))); // NOI18N
        btn_xoasp.setText("Xóa");
        btn_xoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaspActionPerformed(evt);
            }
        });
        jPanel5.add(btn_xoasp);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/back.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/first.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/last.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/next.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_timKiem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtMaLH, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(283, 283, 283))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtGIaMua, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(lblVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtHSD, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(94, 94, 94))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btn_in))
                            .addComponent(lbl_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtMaLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHSD))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDonVi)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGIaMua)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_in, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Thông tin hàng hóa", jPanel3);

        tbl_loaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Loại Sản Phẩm", "Tên Loại Sản Phẩm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_loaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_loaiSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_loaiSP);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/phong_chuan.gif"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(0, 151, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết"));

        btn_themlsp.setBackground(new java.awt.Color(62, 158, 148));
        btn_themlsp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_themlsp.setForeground(new java.awt.Color(255, 255, 255));
        btn_themlsp.setText("Thêm mới ");
        btn_themlsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themlspActionPerformed(evt);
            }
        });

        btn_sualsp.setBackground(new java.awt.Color(31, 131, 221));
        btn_sualsp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_sualsp.setForeground(new java.awt.Color(255, 255, 255));
        btn_sualsp.setText("Cập nhật");
        btn_sualsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sualspActionPerformed(evt);
            }
        });

        btn_xoalsp.setBackground(new java.awt.Color(33, 115, 70));
        btn_xoalsp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_xoalsp.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoalsp.setText("Xóa");
        btn_xoalsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoalspActionPerformed(evt);
            }
        });

        txtMaLoai.setEditable(false);

        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Mã loại SP:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Tên loại SP:");

        btn_moilh.setBackground(new java.awt.Color(62, 158, 148));
        btn_moilh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_moilh.setForeground(new java.awt.Color(255, 255, 255));
        btn_moilh.setText("Mới form");
        btn_moilh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moilhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_moilh))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_themlsp)
                        .addGap(21, 21, 21)
                        .addComponent(btn_sualsp)
                        .addGap(33, 33, 33)
                        .addComponent(btn_xoalsp))
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_themlsp)
                        .addComponent(btn_moilh))
                    .addComponent(btn_sualsp)
                    .addComponent(btn_xoalsp)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cập nhật loại sản phẩm", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_themlspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themlspActionPerformed
        insertLH();
       

    }//GEN-LAST:event_btn_themlspActionPerformed

    private void btn_sualspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sualspActionPerformed
        updateLH();
       
    }//GEN-LAST:event_btn_sualspActionPerformed

    private void btn_xoalspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoalspActionPerformed
        deleteLH();
        
    }//GEN-LAST:event_btn_xoalspActionPerformed

    private void btn_themspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themspMouseClicked
        insert();
    }//GEN-LAST:event_btn_themspMouseClicked

    private void btn_themspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themspActionPerformed
        insert();
        
    }//GEN-LAST:event_btn_themspActionPerformed

    private void btn_suaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaspActionPerformed
        update();
        
    }//GEN-LAST:event_btn_suaspActionPerformed

    private void btn_xoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaspActionPerformed
        delete();
       
    }//GEN-LAST:event_btn_xoaspActionPerformed

    private void btn_moiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_moiMouseClicked
        clearForm();
    }//GEN-LAST:event_btn_moiMouseClicked

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        clearForm();
    }//GEN-LAST:event_btn_moiActionPerformed

    private void lst_loaiHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_loaiHangMouseClicked
        int maLH = lst_loaiHang.getSelectedValue().getMaLH();
        dssp = spDAO.selectSanPhamByLH(maLH);
        fillToTableSP();
    }//GEN-LAST:event_lst_loaiHangMouseClicked

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void tbl_spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_spMouseClicked
        this.row = tbl_sp.getSelectedRow();
        edit();
        if(lst_loaiHang.isSelectionEmpty()){
            btn_moi.setEnabled(false);
        }else{
            btn_moi.setEnabled(true);
            
        }
    }//GEN-LAST:event_tbl_spMouseClicked

    private void lbl_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imgMouseClicked
        chooseImage();
    }//GEN-LAST:event_lbl_imgMouseClicked

    private void tbl_loaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_loaiSPMouseClicked
        this.index = tbl_loaiSP.getSelectedRow(); 
        this.editLoaiHang();
        
    }//GEN-LAST:event_tbl_loaiSPMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        String name = txtTimKiem.getText();
        dssp = spDAO.findByName(name);
        fillToTableSP();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btn_moilhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moilhActionPerformed
        clearFormLH();
    }//GEN-LAST:event_btn_moilhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLySanPham dialog = new QuanLySanPham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btn_in;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_moilh;
    private javax.swing.JButton btn_sualsp;
    private javax.swing.JButton btn_suasp;
    private javax.swing.JButton btn_themlsp;
    private javax.swing.JButton btn_themsp;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoalsp;
    private javax.swing.JButton btn_xoasp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblVAT;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JList<LoaiHang> lst_loaiHang;
    private javax.swing.JTable tbl_loaiSP;
    private javax.swing.JTable tbl_sp;
    private javax.swing.JTextField txtDonVi;
    private javax.swing.JTextField txtGIaMua;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtHSD;
    private javax.swing.JTextField txtMaLH;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtVAT;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setLocationRelativeTo(null);
        loadDataToLoaiHang();
        fillToTableSP();
        fillToTableLoaiHang();
        this.row = -1;
        this.updateStatus();
        
        
    }
    int index = -1;
    int row =-1;
    DefaultComboBoxModel cbo = new DefaultComboBoxModel<>();
    LoaiHangDAO lhDAO = new LoaiHangDAO();
    SanPhamDAO spDAO = new SanPhamDAO();
    List<SanPham> dssp = spDAO.selectAll();; 
    Vector<LoaiHang> dslh;
    DefaultTableModel modelSP;
    DefaultTableModel modelLH;
    
    private void loadDataToLoaiHang() {
       dslh = lhDAO.selectAll_LH();
       lst_loaiHang.setListData(dslh);
       cbo.addElement("Tất cả");
       for(LoaiHang lh : dslh){
           cbo.addElement(lh);
       }
       
       
    }

    private void fillToTableSP() {
        modelSP = (DefaultTableModel) tbl_sp.getModel();
        modelSP.setRowCount(0);
        try {
            for(SanPham sp : dssp){
                Object[] row ={sp.getMaSP(),sp.getTenSP(),sp.getGiaMua(),sp.getGiaBan(),
                sp.getHsd(),sp.getVAT(),sp.getDonVi(),sp.getImg()};
                modelSP.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
        
    }

    private void fillToTableLoaiHang() {
        dslh = lhDAO.selectAll_LH();
        modelLH = (DefaultTableModel) tbl_loaiSP.getModel();
        modelLH.setRowCount(0);
        try {
            for(int i = 0; i<dslh.size();i++){
                Vector v = new Vector();
                v.add(dslh.get(i).getMaLH());
                v.add(dslh.get(i).getTenLH());
                modelLH.addRow(v);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tbl_sp.getRowCount() - 1);
        
        //Trạng thái 
        btn_themlsp.setEnabled(!edit);
        btn_sualsp.setEnabled(edit);
        btn_xoalsp.setEnabled(edit);
        btn_themsp.setEnabled(!edit);
        btn_suasp.setEnabled(edit);
        btn_xoasp.setEnabled(edit);
        
        //Trạng thái điều hướng 
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last); 
        btnLast.setEnabled(edit && !last);
    }
    
    void setForm(SanPham sp){
        txtMaSP.setText(sp.getMaSP()+"");
        txtTenSP.setText(sp.getTenSP());
        txtGIaMua.setText(sp.getGiaMua()+"");
        txtGiaBan.setText(sp.getGiaBan()+"");
        txtVAT.setText(sp.getVAT()+"");
        txtHSD.setText(sp.getHsd());
        txtMaLH.setText(sp.getMaLH()+"");
        txtDonVi.setText(sp.getDonVi());
        if(sp.getImg() == null){
            
        }else{
            lbl_img.setIcon(XImage.read(sp.getImg()));
            lbl_img.setToolTipText(sp.getImg());
        }
  
    }
    
    void setFormLoaiHang(LoaiHang lh){
        txtMaLoai.setText(lh.getMaLH()+"");
        txtTenLoai.setText(lh.getTenLH());
    }
    
    SanPham getForm(){
        SanPham sp = new SanPham(); 
        sp.setMaSP(Integer.parseInt(txtMaSP.getText()));
        sp.setTenSP(txtTenSP.getText());
        sp.setGiaMua(Double.parseDouble(txtGIaMua.getText()));
        sp.setGiaBan(Double.parseDouble(txtGiaBan.getText()));
        sp.setHsd(txtHSD.getText());
        sp.setVAT(Double.parseDouble(txtVAT.getText()));
        sp.setDonVi(txtDonVi.getText());
        sp.setImg(lbl_img.getToolTipText());
        sp.setMaLH(Integer.parseInt(txtMaLH.getText()));
        sp.setMaVach("0000"+sp.getMaSP());
        return sp;
    }
    
    LoaiHang getFormLoaiHang(){
        LoaiHang lh = new LoaiHang();
        lh.setMaLH(Integer.parseInt(txtMaLoai.getText()));
        lh.setTenLH(txtTenLoai.getText());
        return lh;
    }
    
    void clearForm(){
        row = -1;
        SanPham sp = new SanPham(); 
//        sp.setMaSP(spDAO.getMaxID()+1);
        List<Object[]> list = spDAO.getMaxID();
        int maxID = 0;
        for(Object[] row : list){
            maxID = (int) row[0] + 1;
        }
        sp.setMaSP(maxID);
        sp.setMaLH(lst_loaiHang.getSelectedValue().getMaLH());
        this.setForm(sp);
        this.updateStatus();
    }
    
    void edit(){
        int maSP = (int) tbl_sp.getValueAt(this.row, 0);
        SanPham sp = spDAO.selectById(maSP);
        this.setForm(sp);
        this.updateStatus();
    }
    
    void editLoaiHang(){ 
        int maLoai = (int) tbl_loaiSP.getValueAt(this.index, 0);
        LoaiHang lh = lhDAO.selectById(maLoai);
        this.setFormLoaiHang(lh);
        this.updateStatus();
    }
    
    void first(){
        this.row = 0; 
        this.edit();
        tbl_sp.changeSelection(row, WIDTH, false, false);
        tbl_sp.setSelectionBackground(Color.RED);
    }
    
    void next(){
        if(this.row < tbl_sp.getRowCount() -1){
            this.row++;
            this.edit();
            tbl_sp.changeSelection(row, WIDTH, false, false);
            tbl_sp.setSelectionBackground(Color.RED);
        }
    }
    
    void prev(){
        if(this.row > 0){
            this.row--;
            this.edit();
            tbl_sp.changeSelection(row, WIDTH, false, false);
            tbl_sp.setSelectionBackground(Color.RED);
            
        }
    }
    
    void last(){
        this.row = tbl_sp.getRowCount() -1 ;
        this.edit();
        tbl_sp.changeSelection(row, WIDTH, false, false);
        tbl_sp.setSelectionBackground(Color.RED);
    }
    
    void insert(){
//        if(Auth.isManager()){
            SanPham sp = getForm();
            try {
                spDAO.insert(sp);
                new GenerateQRCode().createBarcode(XSqueezeString.squeeze(sp.getTenSP())+".PNG", sp.getMaVach());
                dssp = spDAO.selectAll();
                this.fillToTableSP();
                this.clearForm();
                MsgBox.alert(this, "Thêm mới sản phẩm thành công");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(this, "Thêm mới thất bại");
            }
//        }
    }
    
    void update(){
       if(Auth.isManager()){
           SanPham sp = getForm();
           try {
               spDAO.update(sp);
               dssp = spDAO.selectAll();
               this.fillToTableSP();
               this.clearForm();
               MsgBox.alert(this, "Cập nhật sản phẩm thành công");
           } catch (Exception e) {
               e.printStackTrace();
               MsgBox.alert(this, "Cập nhật thất bại");
           }
       }else{
           MsgBox.alert(this, "Bạn không có quyền cập nhật");
       }
    }
    
    void delete(){
        if(Auth.isManager()){
            
            
        }else if(MsgBox.confirm(this, "Bạn thực sự muốn xoá sản phẩm này?")){
            try {
            int maSP = Integer.parseInt(txtMaSP.getText());
            spDAO.delete(maSP);
            dssp = spDAO.selectAll();
            this.fillToTableSP();
            this.clearForm();
            MsgBox.alert(this, "Xoá thành công 1 mục");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Xoá thất bại");
        }
          }
    }
    
    JFileChooser fileChooser = new JFileChooser();
    void chooseImage(){
        if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            XImage.save(file);
            ImageIcon icon = XImage.read(file.getName());
            lbl_img.setIcon(icon);
            lbl_img.setToolTipText(file.getName());
        }
    }

    private void insertLH() {
        try {
            LoaiHang lh = getFormLoaiHang();
            lh.setMaLH(dslh.size() +1);
            lhDAO.insert(lh);
            MsgBox.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm mới thất bại");
        }

    }

    private void updateLH() {
        try {
            LoaiHang lh = this.getFormLoaiHang();
            lhDAO.update(lh);
            MsgBox.alert(this, "Cập nhật thành công");
            
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!!");
            e.printStackTrace();
        }
        
    }
    
    private void deleteLH(){
        if(MsgBox.confirm(this, "Bạn thực sự muốn xoá mục này?")){
            try {
                int maLoai = Integer.parseInt(txtMaLoai.getText());
                lhDAO.delete(maLoai);
                MsgBox.alert(this, "Xoá thành công 1 mục");
            } catch (Exception e) {
                MsgBox.alert(this, "Xoá thất bại");
                e.printStackTrace();
            }
            
        }
    }

    private void clearFormLH() {
        this.index = -1; 
        txtMaLoai.setText(dslh.size() + 1 + "");
        txtTenLoai.setText("");
    }
}
