/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.ui;

import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import poly.com.dao.HoaDonDAO;
import poly.com.dao.LoaiHangDAO;
import poly.com.dao.NhanVienDAO;
import poly.com.dao.SanPhamDAO;
import poly.com.modal.HoaDon;
import poly.com.modal.LoaiHang;
import poly.com.modal.SanPham;
import poly.com.utils.MsgBox;

/**
 *
 * @author nhatt
 */
public class QuanLyHoaDon extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyHoaDon
     */
    public QuanLyHoaDon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_chiTietHoaDon = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_listHoaDon = new javax.swing.JTable();
        jTextField15 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_inHD = new javax.swing.JButton();
        txtMaHoaDon = new javax.swing.JTextField();
        txtTongTienHD = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_listSP = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        tbl_chiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã HD", "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        tbl_chiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_chiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_chiTietHoaDon);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 610, 180));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Các Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        tbl_listHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Người tạo", "Giờ tạo", "Ngày tạo", "Khách Hàng TT", "Mức giảm", "Điểm thưởng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_listHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_listHoaDonMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_listHoaDon);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Search.png"))); // NOI18N
        jButton6.setText("Tìm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 510, 420));

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mã Hóa Đơn");

        btn_inHD.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_inHD.setText("IN HÓA ĐƠN");
        btn_inHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inHDActionPerformed(evt);
            }
        });

        txtMaHoaDon.setEditable(false);

        txtTongTienHD.setEditable(false);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        tbl_listSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Loại hàng"
            }
        ));
        tbl_listSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listSPMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_listSP);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        btnThem.setBackground(new java.awt.Color(51, 153, 0));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm hoá đơn");
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 153));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xoá hoá đơn");
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(255, 102, 102));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Trash.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật hoá đơn");
        btnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCapNhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tổng tiền HD:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(560, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongTienHD, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_inHD)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_inHD)
                        .addComponent(txtTongTienHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1180, 540));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/b_chuan.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1257, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/hinh-nen-admin-1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 58, 1260, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_listHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listHoaDonMouseClicked
        fillTableHoaDonChiTiet();
        btnXoa.setEnabled(true);
        
    }//GEN-LAST:event_tbl_listHoaDonMouseClicked

    private void tbl_listHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listHoaDonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_listHoaDonMouseEntered

    private void tbl_chiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_chiTietHoaDonMouseClicked
        
        

    }//GEN-LAST:event_tbl_chiTietHoaDonMouseClicked

    private void btn_inHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inHDActionPerformed
       
    }//GEN-LAST:event_btn_inHDActionPerformed

    private void tbl_listSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_listSPMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        addHoaDon();
        this.dispose();
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        updateHoaDon();
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyHoaDon dialog = new QuanLyHoaDon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCapNhat;
    public static javax.swing.JButton btnThem;
    public static javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_inHD;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField15;
    public static javax.swing.JTable tbl_chiTietHoaDon;
    public static javax.swing.JTable tbl_listHoaDon;
    private javax.swing.JTable tbl_listSP;
    public static javax.swing.JTextField txtMaHoaDon;
    public static javax.swing.JTextField txtTongTienHD;
    // End of variables declaration//GEN-END:variables
    
    HoaDonDAO hdDAO = new HoaDonDAO();
    NhanVienDAO nvDAO = new NhanVienDAO();
    SanPhamDAO spDAO = new SanPhamDAO();
    int row = -1;
    DefaultTableModel hdModel ;
    List<HoaDon> dshd = hdDAO.selectAll();
    private void init() {
        this.setLocationRelativeTo(null);
        fillTableHoaDon();
        fillTableSanPham();
        this.row =-1;
        this.updateStatus();
    }

    private void fillTableHoaDon() {
        hdModel = (DefaultTableModel) tbl_listHoaDon.getModel();
        hdModel.setRowCount(0);
        try {
            for(HoaDon hd : dshd){
                Object[] rows = {hd.getMaHD(),nvDAO.selectById(hd.getMaNV()).getHoTen(),
                hd.getGioMua(),hd.getThoiDiemLap(),
                hd.getMaKH(),hd.getMucGiam(),hd.getDiemThuong()};
                hdModel.addRow(rows);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }
    
    DefaultTableModel spModel;
    List<SanPham> dssp;
    LoaiHangDAO lhDAO = new LoaiHangDAO();
    private void fillTableSanPham(){
        spModel = (DefaultTableModel) tbl_listSP.getModel();
        spModel.setRowCount(0);
        dssp = spDAO.selectAll();
        try {
            for(SanPham sp : dssp){
                Object[] rows = {sp.getMaSP(),sp.getTenSP(),sp.getGiaBan(),lhDAO.selectById(sp.getMaLH())};
                spModel.addRow(rows);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }
    
    DefaultTableModel hdctModel;
    List<HoaDon> dshdct ;
    private void fillTableHoaDonChiTiet(){
        hdctModel = (DefaultTableModel) tbl_chiTietHoaDon.getModel();
        hdctModel.setRowCount(0);
        this.row = tbl_listHoaDon.getSelectedRow();
        int maHD = (int) tbl_listHoaDon.getValueAt(this.row, 0);
        dshdct = hdDAO.selectDetailById(maHD);
        try {
            for(HoaDon hd : dshdct){
                Object[] rows = {hd.getMaHD(),
                spDAO.selectById(hd.getMaSP()).getTenSP(),hd.getSoLuong(),
                spDAO.selectById(hd.getMaSP()).getGiaBan()*hd.getSoLuong()};
                hdctModel.addRow(rows);
            }
            txtMaHoaDon.setText(maHD+"");
            txtTongTienHD.setText(hdDAO.selectById(maHD).getTongTienTra()+"");
            
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tbl_listHoaDon.getRowCount() - 1);
        
        btnThem.setEnabled(!edit);
        btnXoa.setEnabled(edit);
        txtMaHoaDon.setEditable(!edit);
        
    }
    
    void addHoaDon(){
        ThemHoaDon thd = new ThemHoaDon(null, true);
        //Lấy giá trị lớn nhất của mã hoá đơn
        List<Object[]> list = hdDAO.getMaxID();
        int maxID = 0;
        for(Object[] row : list){
            maxID = (int) row[0] + 1;
        }
        //Gán cho textField
        ThemHoaDon.txtMaHD.setText(maxID+"");
        
       
        thd.setVisible(true);
    }
    
    void updateHoaDon(){
        ThemHoaDon thd = new ThemHoaDon(null, true);
        if(this.row == -1){
            MsgBox.alert(this, "Bạn chưa chọn mục nào để cập nhật");
        }else{
            
            int maHD = (int) tbl_listHoaDon.getValueAt(this.row, 0);
            int maKH = (int) tbl_listHoaDon.getValueAt(this.row, 4);
            ThemHoaDon.txtMaHD.setText(maHD+"");
            ThemHoaDon.txtKHTT.setText(maKH+"");
            ThemHoaDon.txtTongCong.setText(txtTongTienHD.getText());
            Date ngayTao = (Date) tbl_listHoaDon.getValueAt(this.row, 3);
            ThemHoaDon.jDateNL.setDate(ngayTao);
               
//            Thành tiền 
            double thanhTien = 0;
            System.out.println(tbl_chiTietHoaDon.getRowCount());
            for(int i = 0 ;i<tbl_chiTietHoaDon.getRowCount();i++){
                double tien1SP = (double) tbl_chiTietHoaDon.getValueAt(i, 3);
                thanhTien += tien1SP;
//                System.out.println(thanhTien);
            }
            ThemHoaDon.txtTien.setText(thanhTien +"");
            
            //Khuyến mãi
            double khuyenMai = (thanhTien*(double) tbl_listHoaDon.getValueAt(this.row, 5))/100;
            ThemHoaDon.txtKhuyenMai.setText(khuyenMai+"");
            
            //VAT
            double VAT = 0;
            int i;
            for(i = 0; i<tbl_chiTietHoaDon.getRowCount();i++){
                VAT += (spDAO.selectById((Integer) tbl_chiTietHoaDon.getValueAt(i, 0))).getVAT();
                System.out.println(VAT);
            }
            ThemHoaDon.txtVAT.setText(((VAT)/(i+1))+"");
            
            //Dữ liệu Hoá đơn chi tiết
            DefaultTableModel model = (DefaultTableModel) ThemHoaDon.tblHDCT.getModel();
            model.setRowCount(0);
            
            
            dshdct = hdDAO.selectDetailById(maHD);
            try {
            for(HoaDon hd : dshdct){
                Object[] rows = {hd.getMaHD(),
                spDAO.selectById(hd.getMaSP()).getTenSP(),
                spDAO.selectById(hd.getMaSP()).getGiaBan(),hd.getSoLuong(),
                spDAO.selectById(hd.getMaSP()).getGiaBan()*hd.getSoLuong()};
                model.addRow(rows);
            }
            
                

            } catch (Exception e) {
                MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
                e.printStackTrace();
            }
            
            thd.setVisible(true);
            this.dispose();
        }
        
        
    }
    
}
