/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import poly.com.dao.NhanVienDAO;
import poly.com.dao.PhieuKKDAO;
import poly.com.dao.SanPhamDAO;
import poly.com.dao.ThongKeDAO;
import poly.com.modal.PhieuKiemKe;
import static poly.com.ui.QuanLyNhapXuatHang2.conn;
import static poly.com.ui.QuanLyNhapXuatHang2.jDateNL;
import static poly.com.ui.QuanLyNhapXuatHang2.tblKhoHang;
import poly.com.utils.MsgBox;
import poly.com.utils.XDate;
import poly.com.utils.XJdbc;

/**
 *
 * @author nhatt
 */
public class QuanLyPhieuKiemKe extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhieuKiemKe
     */
    public QuanLyPhieuKiemKe(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        this.init();
        conn = new XJdbc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs_nhaphang = new javax.swing.JTabbedPane();
        pnlKhoHang = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKhoHang = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        lblTimer1 = new javax.swing.JLabel();
        btnInKho = new javax.swing.JButton();
        pnlNhapHang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateNL = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtMaPhieuKK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKiemKe = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtSLTonKho = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btnNhapHang = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThemSP = new javax.swing.JButton();
        btnThemChiTiet = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        pnlListPN = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblTimer2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_listPhieuKK = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnXoaPhieu = new javax.swing.JButton();
        btnThemPhieu = new javax.swing.JButton();
        btnInPhieu1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_ChiTietPhieuKK = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KHO HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        tblKhoHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại hàng", "Mã SP", "Tên SP", "Số lượng", "HSD", "Ngày nhập gần nhất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblKhoHang);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Alarm.png"))); // NOI18N
        jLabel24.setText("Thời gian:");

        lblTimer1.setText("Thời gian thực");
        lblTimer1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnInKho.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnInKho.setForeground(new java.awt.Color(192, 26, 48));
        btnInKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Cash register.png"))); // NOI18N
        btnInKho.setText("IN KHO HÀNG");
        btnInKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInKhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnInKho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblTimer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInKho)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlKhoHangLayout = new javax.swing.GroupLayout(pnlKhoHang);
        pnlKhoHang.setLayout(pnlKhoHangLayout);
        pnlKhoHangLayout.setHorizontalGroup(
            pnlKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
            .addGroup(pnlKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKhoHangLayout.setVerticalGroup(
            pnlKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
            .addGroup(pnlKhoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlKhoHangLayout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabs_nhaphang.addTab("Kho hàng", pnlKhoHang);

        pnlNhapHang.setBackground(new java.awt.Color(255, 255, 204));
        pnlNhapHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NHẬP HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ngày lập phiếu: ");

        jDateNL.setDateFormatString("dd/MM/yyyy");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mã phiếu kiểm kê:");

        txtMaPhieuKK.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Người nhập:");

        tblKiemKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu kiểm kê", "Mã SP", "Số lượng tồn kho", "NV kiểm kê", "Ngày lập phiếu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKiemKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKiemKeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKiemKe);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Alarm.png"))); // NOI18N
        jLabel18.setText("Thời gian:");

        lblTimer.setText("Thời gian thực");
        lblTimer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Mã sản phẩm:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Số lượng tồn:");

        btnNhapHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNhapHang.setForeground(new java.awt.Color(192, 26, 48));
        btnNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Add to basket.png"))); // NOI18N
        btnNhapHang.setText("XÁC NHẬN");
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 153, 153));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(51, 51, 0));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Task list.png"))); // NOI18N
        btnXoa.setText("Xoá chi tiết");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThemSP.setBackground(new java.awt.Color(0, 153, 51));
        btnThemSP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemSP.setText("Chọn mặt hàng");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnThemChiTiet.setBackground(new java.awt.Color(0, 153, 51));
        btnThemChiTiet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/plus.png"))); // NOI18N
        btnThemChiTiet.setText("Thêm chi tiết");
        btnThemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChiTietActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(192, 26, 48));
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Add.png"))); // NOI18N
        btnMoi.setText("FORM MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNhapHangLayout = new javax.swing.GroupLayout(pnlNhapHang);
        pnlNhapHang.setLayout(pnlNhapHangLayout);
        pnlNhapHangLayout.setHorizontalGroup(
            pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhapHangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhapHangLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaPhieuKK, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhapHangLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnlNhapHangLayout.createSequentialGroup()
                .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNhapHangLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlNhapHangLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNhapHangLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateNL, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                        .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlNhapHangLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSLTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNhapHangLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThemSP)
                                .addGap(1, 1, 1))))
                    .addGroup(pnlNhapHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhapHangLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhapHangLayout.createSequentialGroup()
                                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhapHangLayout.createSequentialGroup()
                                .addComponent(btnThemChiTiet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlNhapHangLayout.setVerticalGroup(
            pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblTimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNhapHangLayout.createSequentialGroup()
                        .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDateNL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNhapHangLayout.createSequentialGroup()
                        .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemSP))
                        .addGap(18, 18, 18)
                        .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtSLTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnThemChiTiet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnlNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapHang)
                    .addComponent(btnMoi))
                .addGap(38, 38, 38))
        );

        tabs_nhaphang.addTab("Thêm phiếu kiểm kê", pnlNhapHang);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH PHIẾU NHẬP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Alarm.png"))); // NOI18N
        jLabel25.setText("Thời gian:");

        lblTimer2.setText("Thời gian thực");
        lblTimer2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phiếu kiểm kê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        tbl_listPhieuKK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu kiểm kê", "Mã nhân viên", "Họ tên NV", "Thời điểm lập"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_listPhieuKK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listPhieuKKMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_listPhieuKK);

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Search.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(txtTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnXoaPhieu.setBackground(new java.awt.Color(255, 255, 153));
        btnXoaPhieu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaPhieu.setForeground(new java.awt.Color(192, 26, 48));
        btnXoaPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Delete.png"))); // NOI18N
        btnXoaPhieu.setText("HUỶ PHIẾU");
        btnXoaPhieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoaPhieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoaPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhieuActionPerformed(evt);
            }
        });

        btnThemPhieu.setBackground(new java.awt.Color(51, 153, 0));
        btnThemPhieu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemPhieu.setForeground(new java.awt.Color(192, 26, 48));
        btnThemPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Add.png"))); // NOI18N
        btnThemPhieu.setText("THÊM PHIẾU");
        btnThemPhieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThemPhieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThemPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuActionPerformed(evt);
            }
        });

        btnInPhieu1.setBackground(new java.awt.Color(0, 153, 153));
        btnInPhieu1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnInPhieu1.setForeground(new java.awt.Color(192, 26, 48));
        btnInPhieu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Cash register.png"))); // NOI18N
        btnInPhieu1.setText("IN PHIẾU NHẬP");
        btnInPhieu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInPhieu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInPhieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInPhieu1ActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết phiếu kiểm kê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        tbl_ChiTietPhieuKK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phiếu Kiêm Kê", "Mã SP", "Số Lượng Tồn kho"
            }
        ));
        jScrollPane5.setViewportView(tbl_ChiTietPhieuKK);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThemPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInPhieu1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblTimer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnThemPhieu)
                        .addGap(57, 57, 57)
                        .addComponent(btnXoaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnInPhieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlListPNLayout = new javax.swing.GroupLayout(pnlListPN);
        pnlListPN.setLayout(pnlListPNLayout);
        pnlListPNLayout.setHorizontalGroup(
            pnlListPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
            .addGroup(pnlListPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListPNLayout.setVerticalGroup(
            pnlListPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
            .addGroup(pnlListPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs_nhaphang.addTab("Danh sách phiếu kiểm kê", pnlListPN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs_nhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs_nhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInPhieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInPhieu1ActionPerformed
        if(row == -1){
            MsgBox.alert(this, "Vui lòng chọn phiếu để in");
        }else{
            this.row = tbl_listPhieuKK.getSelectedRow();
            int maPN = (int) tbl_listPhieuKK.getValueAt(this.row, 0);
            printBill(maPN, "PNReport.jrxml");
        }
    }//GEN-LAST:event_btnInPhieu1ActionPerformed

    private void btnThemPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhieuActionPerformed
        selectTab(1);
    }//GEN-LAST:event_btnThemPhieuActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void tbl_listPhieuKKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listPhieuKKMouseClicked
        this.row = tbl_listPhieuKK.getSelectedRow();
        fillToTableChiTietPhieuNhap();
    }//GEN-LAST:event_tbl_listPhieuKKMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChiTietActionPerformed
        addDetailsPN();
    }//GEN-LAST:event_btnThemChiTietActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        addProduct();
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        removeItem();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        insertPKK();
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void tblKiemKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKiemKeMouseClicked
        if(kkModel.getRowCount() != 0){
            filltoForm();
        }
    }//GEN-LAST:event_tblKiemKeMouseClicked

    private void btnInKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInKhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInKhoActionPerformed

    private void btnXoaPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhieuActionPerformed
        destroyItem();
    }//GEN-LAST:event_btnXoaPhieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuKiemKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyPhieuKiemKe dialog = new QuanLyPhieuKiemKe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInKho;
    private javax.swing.JButton btnInPhieu1;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnThemChiTiet;
    public static javax.swing.JButton btnThemPhieu;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    public static javax.swing.JButton btnXoaPhieu;
    public static com.toedter.calendar.JDateChooser jDateNL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTimer1;
    private javax.swing.JLabel lblTimer2;
    private javax.swing.JPanel pnlKhoHang;
    private javax.swing.JPanel pnlListPN;
    private javax.swing.JPanel pnlNhapHang;
    private javax.swing.JTabbedPane tabs_nhaphang;
    public static javax.swing.JTable tblKhoHang;
    public static javax.swing.JTable tblKiemKe;
    public static javax.swing.JTable tbl_ChiTietPhieuKK;
    public static javax.swing.JTable tbl_listPhieuKK;
    public static javax.swing.JTextField txtMaPhieuKK;
    public static javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNhanVien;
    public static javax.swing.JTextField txtSLTonKho;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    int row = -1;
    DefaultTableModel kkModel ;
    PhieuKKDAO kkDAO = new PhieuKKDAO();
    private void init() {
        setLocationRelativeTo(null);
        this.fillTableKhoHang();
        this.fillTablePhieuKK();
        setOclock();
        
        this.getMaxID();
        jDateNL.setDate(XDate.now());
    }
    
    private void setOclock() {
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat fomarter = new SimpleDateFormat("hh:mm:ss a");
                String text = fomarter.format(now);
                lblTimer.setText(text);
                lblTimer1.setText(text);
                lblTimer2.setText(text);
                
            }
        }).start();
    }
    
    public void selectTab(int index){
        tabs_nhaphang.setSelectedIndex(index);
    }
    
    
    private void fillTableKhoHang() {
        SanPhamDAO spDAO = new SanPhamDAO();
        ThongKeDAO tkDAO = new ThongKeDAO();
        DefaultTableModel khModel = (DefaultTableModel) tblKhoHang.getModel();
        khModel.setRowCount(0);
        List<Object[]> list = tkDAO.getKhoHang();
        for(Object[] row : list){
            //Lấy mã loại hàng
            int maLH = spDAO.selectById((int)row[0]).getMaLH();
            //TênSP,HSD
            String tenSP = spDAO.selectById((int)row[0]).getTenSP();
            String HSD = spDAO.selectById((int)row[0]).getHsd();
            //ADD VÀO ROW
            khModel.addRow(new Object[]{maLH,row[0],tenSP,row[1],HSD,row[2]});  
        }
    }
    
    List<PhieuKiemKe> dskk;
    private void fillTablePhieuKK(){
        NhanVienDAO nvDAO = new NhanVienDAO();
        kkModel = (DefaultTableModel) tbl_listPhieuKK.getModel();
        kkModel.setRowCount(0);
        dskk = kkDAO.selectAll();
        try {
            for(PhieuKiemKe pkk : dskk){
                Object[] rows = {pkk.getMaPhieuKK(),pkk.getMaNV(),nvDAO.selectById(pkk.getMaNV()).getHoTen(),pkk.getThoiDiemLap()};
                kkModel.addRow(rows);
                
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }

    DefaultTableModel modelCTKK ;
    List<PhieuKiemKe> ctkkList;
    private void fillToTableChiTietPhieuNhap() {
        modelCTKK = (DefaultTableModel) tbl_ChiTietPhieuKK.getModel();
        modelCTKK.setRowCount(0);
        this.row = tbl_listPhieuKK.getSelectedRow();
        int maPKK = (int) tbl_listPhieuKK.getValueAt(this.row, 0);
        ctkkList = kkDAO.selectDetailsByID(maPKK);
        try {
            for(PhieuKiemKe pkk : ctkkList){
                Object[] rows = {pkk.getMaPhieuKK(),pkk.getMaSP(),pkk.getSLTonKho()};
                modelCTKK.addRow(rows);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }
    
    private void addProduct(){
        NhapSanPham.so = 0;
        new NhapSanPham(this, true).setVisible(true);
    }
    
    int maxID;
    private void getMaxID() {
        List<Object[]> list = kkDAO.getMaxID();
        
        for (Object[] row : list) {
            maxID = (int) row[0];
        }
        //Gán cho textField
        txtMaPhieuKK.setText((maxID+1) +"");

    }
    
    void clearForm(){
        kkModel = (DefaultTableModel) tblKiemKe.getModel();
        kkModel.setRowCount(0);
        this.getMaxID();
        jDateNL.setDate(XDate.now());
        txtNhanVien.setText("");
        txtSLTonKho.setText("");
        txtMaSP.setText("");
    }
    
    private void printBill(int id,String nameReport){
        try {
        Hashtable map = new Hashtable();
            //JasperReport
            JasperReport jr = JasperCompileManager.compileReport("src/poly/com/ui/"+nameReport);
            map.put("MaPN",(id));
            //JasperPrint
            @SuppressWarnings("unchecked")
            JasperPrint jp = JasperFillManager.fillReport(jr, map, XJdbc.conn);
            //JasperView
            JasperViewer.viewReport(jp,false);
            //JasperExport
            JasperExportManager.exportReportToPdfFile(jp, "PhieuKiemKe.pdf");
        } catch (JRException ex) {

            ex.printStackTrace();
        }
    }
    
    private void removeItem() {
        kkModel = (DefaultTableModel) tblKiemKe.getModel();
        this.row = tblKiemKe.getSelectedRow();
        if (MsgBox.confirm(this, "Bạn muốn xoá sản phẩm này?")) {
            kkModel.removeRow(row);
        }
    }
    
    public static XJdbc conn;
    private void insertPKK() {
        getMaxID();
        System.out.println("Xuất PN: "+maxID);
        kkModel = (DefaultTableModel) tblKiemKe.getModel();
        
        //INSERT PN
        PhieuKiemKe pkk = new PhieuKiemKe();
        
        pkk.setMaNV(Integer.parseInt(txtNhanVien.getText()));
        pkk.setThoiDiemLap(XDate.convertDate(jDateNL.getDate()));

        try {   
            kkDAO.insert(pkk);
            MsgBox.alert(this, "Thêm phiếu nhập thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm phiếu nhập không thành công");
        }
        
        //INSERT PNCT 
        try {
            pkk.setMaPhieuKK(maxID +1);
            for(int i = 0;i<tblKiemKe.getRowCount();i++){
                pkk.setMaSP((int) tblKiemKe.getValueAt(i, 1));
                pkk.setSLTonKho((int) tblKiemKe.getValueAt(i, 2));
                kkDAO.insertKKCT(pkk);
                System.out.println("Thêm PNCT thành công");
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Thêm PNCT không thành công");
        }
        
        printBill(maxID+1,"PKKReport.jrxml");
        
    }
    
    private void filltoForm() {
        this.row = tblKiemKe.getSelectedRow();
        txtMaPhieuKK.setText((int) tblKiemKe.getValueAt(this.row, 0)+"");
        txtNhanVien.setText((int) tblKiemKe.getValueAt(this.row, 3)+"");
        jDateNL.setDate((Date) tblKiemKe.getValueAt(this.row, 4));
        txtMaSP.setText((int)tblKiemKe.getValueAt(this.row, 1)+"");
        txtSLTonKho.setText((int)tblKiemKe.getValueAt(this.row, 2)+"");
        
    }
    
    private void addDetailsPN() {
        kkModel = (DefaultTableModel) tblKiemKe.getModel();
        Object[] rows = {Integer.parseInt(txtMaPhieuKK.getText()),Integer.parseInt(txtMaSP.getText())
                ,Integer.parseInt(txtSLTonKho.getText()),Integer.parseInt(txtNhanVien.getText()),jDateNL.getDate()};
        kkModel.addRow(rows);
    }

    private void destroyItem() {
        this.row = tbl_listPhieuKK.getSelectedRow();
        if(MsgBox.confirm(this, "Bạn thực sự muốn huỷ phiếu này?")){
            PhieuKiemKe pkk = new PhieuKiemKe();
            pkk.setMaPhieuKK((int) tbl_listPhieuKK.getValueAt(this.row, 0));
            pkk.setThoiDiemLap(XDate.convertDate(pkk.getThoiDiemLap()));
            kkDAO.update(pkk);
            kkDAO.updateCTPX(pkk);
            MsgBox.alert(this, "HUỶ PHIẾU KIỂM KÊ THÀNH CÔNG");
        }
    }
}
