/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.com.ui;

import java.util.Random;
import poly.com.dao.NhanVienDAO;
import poly.com.modal.NhanVien;
import poly.com.utils.GenerateQRCode;
import poly.com.utils.MsgBox;
import poly.com.utils.SendEmailToRecover;

/**
 *
 * @author nhatt
 */
public class QuenMatKhau extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhau
     */
    String code ;
    NhanVienDAO nvDAO = new NhanVienDAO();
    public QuenMatKhau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.init(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCheck = new javax.swing.JLabel();
        lblMK = new javax.swing.JLabel();
        lblTK = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        txtTaiKhoan = new javax.swing.JTextField();
        lblMK2 = new javax.swing.JLabel();
        txtMatKhau2 = new javax.swing.JPasswordField();
        lblXN = new javax.swing.JLabel();
        lblThongBao = new javax.swing.JLabel();
        BtnHuyBo = new javax.swing.JButton();
        btnLayLaiMK = new javax.swing.JButton();
        txtXacNhan = new javax.swing.JTextField();
        btnGuiLaiMa = new javax.swing.JButton();
        lblMK1 = new javax.swing.JLabel();
        lblmk2 = new javax.swing.JLabel();
        lblxn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("QUÊN MẬT KHẨU");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khôi phục bằng tài khoản gmail");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Email của bạn:");

        txtEmail.setBackground(new java.awt.Color(204, 204, 255));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        lblCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Accept.png"))); // NOI18N

        lblMK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMK.setForeground(new java.awt.Color(153, 0, 153));
        lblMK.setText("Mật khẩu mới:");

        lblTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTK.setForeground(new java.awt.Color(153, 0, 153));
        lblTK.setText("Tài khoản:");

        txtMatKhau.setEditable(false);
        txtMatKhau.setBackground(new java.awt.Color(204, 204, 255));
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        txtTaiKhoan.setEditable(false);
        txtTaiKhoan.setBackground(new java.awt.Color(204, 204, 255));
        txtTaiKhoan.setForeground(new java.awt.Color(255, 0, 0));

        lblMK2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMK2.setForeground(new java.awt.Color(153, 0, 153));
        lblMK2.setText("Nhập lại mật khẩu:");

        txtMatKhau2.setEditable(false);
        txtMatKhau2.setBackground(new java.awt.Color(204, 204, 255));

        lblXN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblXN.setForeground(new java.awt.Color(153, 0, 153));
        lblXN.setText("Mã xác nhận:");

        lblThongBao.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblThongBao.setForeground(new java.awt.Color(255, 0, 0));
        lblThongBao.setText("1 mã xác nhận đã được gởi về mail của bạn !!!");

        BtnHuyBo.setBackground(new java.awt.Color(255, 102, 102));
        BtnHuyBo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Exit.png"))); // NOI18N
        BtnHuyBo.setText("Huỷ bỏ");
        BtnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHuyBoActionPerformed(evt);
            }
        });

        btnLayLaiMK.setBackground(new java.awt.Color(0, 153, 153));
        btnLayLaiMK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLayLaiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/update.png"))); // NOI18N
        btnLayLaiMK.setText("Lấy lại mật khẩu");
        btnLayLaiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayLaiMKActionPerformed(evt);
            }
        });

        txtXacNhan.setEditable(false);
        txtXacNhan.setBackground(new java.awt.Color(204, 204, 255));
        txtXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXacNhanActionPerformed(evt);
            }
        });

        btnGuiLaiMa.setForeground(new java.awt.Color(0, 153, 153));
        btnGuiLaiMa.setText("Gửi lại mã");
        btnGuiLaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiLaiMaActionPerformed(evt);
            }
        });

        lblMK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Warning.png"))); // NOI18N

        lblmk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Warning.png"))); // NOI18N

        lblxn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/image/icon/Warning.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblXN, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblMK)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblTK)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEmail)
                                            .addComponent(txtTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblMK2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMatKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblThongBao))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCheck)
                                    .addComponent(lblMK1)
                                    .addComponent(lblmk2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblxn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuiLaiMa))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLayLaiMK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTK, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblMK, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMK1)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblMK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMatKhau2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(lblmk2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblXN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(5, 5, 5))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuiLaiMa)))
                    .addComponent(lblxn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHuyBo)
                    .addComponent(btnLayLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        NhanVien nv = nvDAO.selectByEmail(txtEmail.getText());
        if(nv != null){
            lblCheck.setVisible(true);
            txtTaiKhoan.setText(nv.getTaiKhoan());
            txtXacNhan.setEditable(true);
            txtMatKhau.setEditable(true);
            txtMatKhau2.setEditable(true);
            // Random code 
            Random rd = new Random();
            code= String.valueOf(rd.nextInt(20000));
            System.out.println(code);
            SendEmailToRecover.CodeToRecover(txtEmail.getText(), code+"");
            lblThongBao.setVisible(true);
        //
        }
    }//GEN-LAST:event_txtEmailKeyReleased
    
    private void btnGuiLaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiLaiMaActionPerformed
        // Random code 
            Random rd = new Random();
            code= String.valueOf(rd.nextInt(20000));
            System.out.println(code);
            SendEmailToRecover.CodeToRecover(txtEmail.getText(), code+"");
            btnGuiLaiMa.setEnabled(false);
        //
    }//GEN-LAST:event_btnGuiLaiMaActionPerformed

    private void btnLayLaiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayLaiMKActionPerformed
        String mkMoi = new String(txtMatKhau.getPassword()) ;
        String xnMK = new String(txtMatKhau2.getPassword());
        String tk = new String(txtTaiKhoan.getText());
        if(mkMoi.equals(xnMK)){
            if(txtXacNhan.getText().equals(code)){
                try {
                    nvDAO.updatePassword(txtTaiKhoan.getText(),new String(txtMatKhau.getPassword()));
                    MsgBox.alert(this, "Lấy lại mật khẩu thành công");
                    GenerateQRCode QR = new GenerateQRCode();
//                    QR.generateQRCode(tk, "Barcode\\");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }else{
                MsgBox.alert(this, "Mã xác nhận không đúng");
                lblxn.setVisible(true);
                txtMatKhau.setFocusable(true);
                
            }
        }else{
            MsgBox.alert(this, "Nhập lại mật khẩu không đúng");
            lblMK1.setVisible(true);
            lblmk2.setVisible(true);
            txtXacNhan.setFocusable(true);
            
        }
        
        
    }//GEN-LAST:event_btnLayLaiMKActionPerformed

    private void BtnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHuyBoActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnHuyBoActionPerformed

    private void txtXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXacNhanActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhau dialog = new QuenMatKhau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHuyBo;
    private javax.swing.JButton btnGuiLaiMa;
    private javax.swing.JButton btnLayLaiMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblMK;
    private javax.swing.JLabel lblMK1;
    private javax.swing.JLabel lblMK2;
    private javax.swing.JLabel lblTK;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JLabel lblXN;
    private javax.swing.JLabel lblmk2;
    private javax.swing.JLabel lblxn;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JPasswordField txtMatKhau2;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtXacNhan;
    // End of variables declaration//GEN-END:variables

    private void init() {
        lblCheck.setVisible(false);
        lblThongBao.setVisible(false);
        lblMK1.setVisible(false);
        lblmk2.setVisible(false);
        lblxn.setVisible(false);
        this.setLocationRelativeTo(null);
    }
    
    
}
